In [1]:
import pandas as pd
import numpy as np


In [2]:
dataset = pd.read_csv("austin_weather.csv")

In [3]:
dataset.tail()

Date  TempHighF  TempAvgF  TempLowF DewPointHighF DewPointAvgF  \
1314  2017-07-27        103        89        75            71           67   
1315  2017-07-28        105        91        76            71           64   
1316  2017-07-29        107        92        77            72           64   
1317  2017-07-30        106        93        79            70           68   
1318  2017-07-31         99        88        77            66           61   

     DewPointLowF HumidityHighPercent HumidityAvgPercent HumidityLowPercent  \
1314           61                  82                 54                 25   
1315           55                  87                 54                 20   
1316           55                  82                 51                 19   
1317           63                  69                 48                 27   
1318           54                  64                 43                 22   

      ... SeaLevelPressureAvgInches SeaLevelPressureLowInches  \
1314  ...                     29.97                     29.88   
1315  ...                      29.9                     29.81   
1316  ...                     29.86                     29.79   
1317  ...                     29.91                     29.87   
1318  ...                     29.97                     29.91   

     VisibilityHighMiles VisibilityAvgMiles VisibilityLowMiles WindHighMPH  \
1314                  10                 10                 10          12   
1315                  10                 10                 10          14   
1316                  10                 10                 10          12   
1317                  10                 10                 10          13   
1318                  10                 10                 10          12   

     WindAvgMPH WindGustMPH PrecipitationSumInches Events  
1314          5          21                      0         
1315          5          20                      0         
1316          4          17                      0         
1317          4          20                      0         
1318          4          20                      0         

[5 rows x 21 columns]

In [4]:
dataset.head(1)

Date  TempHighF  TempAvgF  TempLowF DewPointHighF DewPointAvgF  \
0  2013-12-21         74        60        45            67           49   

  DewPointLowF HumidityHighPercent HumidityAvgPercent HumidityLowPercent  ...  \
0           43                  93                 75                 57  ...   

  SeaLevelPressureAvgInches SeaLevelPressureLowInches VisibilityHighMiles  \
0                     29.68                     29.59                  10   

  VisibilityAvgMiles VisibilityLowMiles WindHighMPH WindAvgMPH WindGustMPH  \
0                  7                  2          20          4          31   

  PrecipitationSumInches               Events  
0                   0.46  Rain , Thunderstorm  

[1 rows x 21 columns]

In [5]:
dataset.isnull().any()

Date                          False
TempHighF                     False
TempAvgF                      False
TempLowF                      False
DewPointHighF                 False
DewPointAvgF                  False
DewPointLowF                  False
HumidityHighPercent           False
HumidityAvgPercent            False
HumidityLowPercent            False
SeaLevelPressureHighInches    False
SeaLevelPressureAvgInches     False
SeaLevelPressureLowInches     False
VisibilityHighMiles           False
VisibilityAvgMiles            False
VisibilityLowMiles            False
WindHighMPH                   False
WindAvgMPH                    False
WindGustMPH                   False
PrecipitationSumInches        False
Events                        False
dtype: bool

In [6]:
dataset=dataset.drop(['Date'],axis=1)

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset["Events"]=le.fit_transform(dataset["Events"])
dataset["PrecipitationSumInches"]=le.fit_transform(dataset["PrecipitationSumInches"])
dataset["SeaLevelPressureHighInches"]=le.fit_transform(dataset["SeaLevelPressureHighInches"])
dataset["SeaLevelPressureLowInches"]=le.fit_transform(dataset["SeaLevelPressureLowInches"])
dataset["VisibilityHighMiles"]=le.fit_transform(dataset["VisibilityHighMiles"])
dataset["VisibilityAvgMiles"]=le.fit_transform(dataset["VisibilityAvgMiles"])
dataset["VisibilityLowMiles"]=le.fit_transform(dataset["VisibilityLowMiles"])
dataset["TempHighF"]=le.fit_transform(dataset["TempHighF"])
dataset["TempAvgF"]=le.fit_transform(dataset["TempAvgF"])
dataset["TempLowF"]=le.fit_transform(dataset["TempLowF"])
dataset["DewPointHighF"]=le.fit_transform(dataset["DewPointHighF"])
dataset["DewPointAvgF"]=le.fit_transform(dataset["DewPointAvgF"])
dataset["DewPointLowF"]=le.fit_transform(dataset["DewPointLowF"])
dataset["HumidityHighPercent"]=le.fit_transform(dataset["HumidityHighPercent"])
dataset["HumidityAvgPercent"]=le.fit_transform(dataset["HumidityAvgPercent"])
dataset["HumidityLowPercent"]=le.fit_transform(dataset["HumidityLowPercent"])
dataset["SeaLevelPressureAvgInches"]=le.fit_transform(dataset["SeaLevelPressureAvgInches"])
dataset["WindHighMPH"]=le.fit_transform(dataset["WindHighMPH"])
dataset["WindAvgMPH"]=le.fit_transform(dataset["WindAvgMPH"])
dataset["WindGustMPH"]=le.fit_transform(dataset["WindGustMPH"])


In [8]:
x=dataset.iloc[:,0:19].values
y=dataset.iloc[:,19].values

In [9]:
type(x)

numpy.ndarray

In [10]:
y

array([7, 0, 0, ..., 0, 0, 0])

In [11]:
x[:,3]

array([50, 26, 14, ..., 55, 53, 49], dtype=int64)

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [13]:
x.shape

(1319, 19)

In [14]:
y.shape

(1319,)

In [15]:
x_train.shape

(1055, 19)

In [16]:
y_test.shape

(264,)

In [17]:
x_train[:,3]

array([54, 25, 40, ..., 51, 57, 57], dtype=int64)

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)



In [19]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

# Predicting the Test set results


DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

In [20]:
y_pred = classifier.predict(x_test)



In [21]:
y_pred

array([0, 7, 0, 0, 0, 3, 7, 0, 8, 0, 0, 0, 0, 7, 0, 0, 5, 5, 0, 0, 0, 0,
       2, 0, 0, 0, 0, 3, 7, 7, 0, 0, 7, 0, 0, 7, 0, 0, 0, 7, 3, 0, 0, 5,
       0, 0, 5, 3, 0, 7, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 7, 7, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0,
       5, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 5, 0, 5, 0, 0, 0, 0,
       7, 0, 0, 0, 0, 5, 0, 5, 0, 1, 3, 0, 0, 5, 7, 0, 0, 1, 0, 7, 0, 5,
       0, 0, 0, 0, 5, 0, 3, 0, 0, 0, 7, 0, 7, 7, 7, 0, 0, 0, 0, 7, 0, 0,
       0, 5, 8, 0, 0, 1, 7, 0, 0, 0, 5, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 7, 8, 7, 0, 0, 8, 0, 5, 0, 0, 7, 0, 0, 0, 0, 7, 0,
       0, 5, 5, 0, 7, 5, 0, 0, 0, 0, 0, 7, 0, 5, 0, 5, 7, 0, 0, 0, 0, 0,
       3, 2, 0, 0, 5, 0, 0, 8, 0, 5, 0, 0, 5, 5, 5, 8, 5, 3, 0, 0, 0, 0,
       0, 0, 2, 5, 0, 6, 0, 0, 7, 2, 5, 7, 0, 0, 0, 3, 7, 0, 7, 0, 0, 0])

In [22]:
y_test

array([0, 5, 0, 0, 0, 3, 5, 0, 0, 0, 5, 0, 0, 7, 0, 0, 5, 5, 0, 0, 0, 0,
       2, 0, 0, 0, 0, 1, 7, 7, 0, 0, 5, 0, 0, 5, 0, 0, 0, 7, 3, 0, 0, 7,
       0, 0, 7, 3, 0, 7, 0, 0, 0, 0, 8, 5, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0,
       0, 7, 0, 5, 5, 0, 0, 0, 5, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0,
       5, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 7, 0, 0, 0, 0,
       7, 0, 0, 0, 0, 5, 0, 0, 0, 1, 3, 0, 0, 5, 7, 0, 0, 1, 0, 5, 0, 5,
       0, 0, 0, 0, 7, 0, 3, 0, 0, 0, 5, 0, 7, 7, 5, 0, 0, 8, 0, 5, 0, 0,
       0, 0, 0, 0, 0, 1, 7, 0, 0, 0, 5, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 7, 0, 5, 0, 0, 0, 0, 5, 0, 0, 7, 0, 0, 0, 0, 5, 0,
       0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 7, 0, 7, 0, 5, 7, 0, 0, 0, 0, 0,
       3, 2, 0, 0, 7, 0, 0, 0, 0, 5, 0, 0, 5, 5, 7, 0, 0, 3, 0, 0, 0, 0,
       0, 0, 3, 5, 0, 0, 0, 0, 7, 2, 5, 7, 0, 0, 0, 3, 7, 5, 7, 0, 0, 0])

In [23]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8295454545454546

In [24]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [25]:
cm

array([[169,   0,   0,   0,   7,   1,   0,   6],
       [  0,   3,   0,   1,   0,   0,   0,   0],
       [  0,   0,   3,   0,   0,   0,   0,   0],
       [  0,   0,   1,   8,   0,   0,   0,   0],
       [  4,   0,   0,   0,  17,   0,  14,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0],
       [  1,   0,   0,   0,   8,   0,  19,   0],
       [  2,   0,   0,   0,   0,   0,   0,   0]], dtype=int64)

In [26]:
x_test.shape

(264, 19)

In [27]:
ypred1 = classifier.predict(sc.transform(np.array([[92,81,70,70,66,60,97,67,36,29.88,29.82,29.78,10,10,10,14,5,25,0]])))

In [28]:
ypred1

array([8])

In [29]:
import pickle
pickle.dump(classifier,open('future wheather predection.pkl','wb'))
model=pickle.load(open('future wheather predection.pkl','rb'))



In [30]:
from sklearn.externals import joblib
scaler_filename = "future wheather predection.save"
joblib.dump(sc, scaler_filename)

C:\Users\ADMIN\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


['future wheather predection.save']